#!/usr/bin/python3
import gspread
import smtplib
import ssl
import imapclient
import os
import email
import sys

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


class EmailBot:
    
    def __init__(self):
        
        self.search = 'SUBJECT','test1'
        self.email = 'kellyservices.bot@gmail.com'
        self.pw = 'Dylandylan2'
        self.folder = 'INBOX'
        self.readonly = False
        self.host = 'imap.gmail.com'
        self.directory = '/home/pi/Desktop/Python/Bot/Temp'
        self.__email_connect()
        self.file = ''
        
        
    def __email_connect(self):
    
        self.mail = imapclient.IMAPClient(self.host, ssl = True)
        accountdetails = self.mail.login(self.email, self.pw)
        print(accountdetails)
        selected_info = self.mail.select_folder(self.folder, readonly = self.readonly)
        
    def email_search(self):
        
        self.id = self.mail.search([self.search])
        
        for uid, message_data in self.mail.fetch(self.id, 'RFC822').items():
            email_message = email.message_from_bytes(message_data[b'RFC822'])
            print(uid, email_message.get('From'), email_message.get('Subject'))
            
            if email_message.get_content_maintype() != 'multipart':
                print('No attachment found')
                return
        
            for part in email_message.walk():

                if part.get_content_maintype() != 'multipart' and part.get('Content-Disposition') is not None:
                    print('Saved!')
                    open(self.directory + '/' + part.get_filename(), 'wb').write(part.get_payload(decode=True))
                    self.filedir = (self.directory + '/' + part.get_filename())
                    
    def file_dir(self):
        
        return self.filedir
    
    def disconnect(self):
        os.remove(self.filedir)
        print('File deleted, disconnected.')
        pass #disconnect

class Gsheets:
    
    def __init__(self):
        pass
    
    def sheet_connect(self):
        
        from oauth2client.service_account import ServiceAccountCredentials
        scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
        creds = ServiceAccountCredentials.from_json_keyfile_name('/home/pi/Desktop/Python/Bot/bot_cred.json', scope)
        client = gspread.authorize(creds)
        global sheet
        sheet = client.open("Candidate Tracker").sheet1

class Main:
    
    employee_dict = {
    'April': 'AA',
    'Gaby': 'GO'
    }
    
    def __init__(self):
        
    def open_sheet(self, directory):
        
        
        
    def SendEmail(self):
            
        password = 'Dylandylan2'
        sent_from = 'kellyservices.bot@gmail.com'
        to = [sender]  
        subject = ('Request received. Tracker updated.') 
        body = ''
        msg = MIMEMultipart()
        msg['To'] =', '.join(to)
        msg['From'] = sent_from
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))

        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(sent_from, password)
            server.sendmail(sent_from, to, msg.as_string())

print('Beginning')
bot = EmailBot()
bot.email_scrape()
bot.disconnect()
exit()










